<!-- Load Scripts -->
{!! Html::script ('assets/js/jquery.js') !!}
{!! Html::script ('assets/js/responsiveslides.js') !!}
{!! Html::script ('assets/js/lightbox.js') !!}
{!! Html::script ('assets/js/slick.js') !!}
{!! Html::script ('assets/js/persian.js') !!}
{!! Html::script ('assets/js/app.js') !!}
{!! Html::script ('assets/js/jquery.form.min.js') !!}
{!! Html::script ('assets/js/forms.js') !!}