@include("manage.posts.editor-moderateNote")
@include("manage.posts.editor-title")
@include("manage.posts.editor-text")
@include("manage.posts.editor-event")
@include("manage.posts.editor-price")
@include("manage.posts.editor-meta")
@include("manage.posts.editor-album")