@include("manage.posts.editor-publish")
@include("manage.posts.editor-schedule")
@include("manage.posts.editor-image")
@include("manage.posts.editor-categories")
@include("manage.posts.editor-options")
